#                                                            PYTHON

In [4]:
print("Hello World")

Hello World


In [5]:
def welcome(name):
    if name == "Vid":
        print("Hello, Vid!")
    else:
        print("Hello, stranger!")

# Call the function
welcome("Vid")

Hello, Vid!


In [6]:
# En preprost komentar

In [7]:
'''
To je docstring, za bolj obsežno razlago kode
'''

'\nTo je doctring, za bolj obsežno razlago kode\n'

# LISTS

Jih lahko manipuliramo

In [30]:
fruits = ["apple", "banana", "orange"]

In [9]:
mixed_list = [1, "apple", 3.14, True]

In [10]:
empty_list = []

In [14]:
word_list = list("Python")   # list() constructor
print(word_list)

['P', 'y', 't', 'h', 'o', 'n']


In [15]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]  # multidimensional (nested lists)

In [18]:
first_fruit = fruits[0]
last_fruit = fruits[-1]
print(first_fruit)
print(last_fruit)

apple
orange


In [19]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]
# Basic slicing
subset1 = numbers[2:6] # Elements from index 2 to 5
print(subset1) # Output: [3, 4, 5, 6]
# Slicing with step
subset2 = numbers[1:8:2] # Elements from index 1 to 7, every 2nd element
print(subset2) # Output: [2, 4, 6, 8]
# Slicing with negative indices
subset3 = numbers[-5:-2] # Elements from index -5 to -3
print(subset3) # Output: [5, 6, 7]

[3, 4, 5, 6]
[2, 4, 6, 8]
[5, 6, 7]


In [31]:
fruits[1] = "kiwi"
fruits[-1] = "grape"
fruits.append("peach") #isto je fruits.extend("peach") oziroma fruits += ["peach"]
fruits.insert(1, "cherry")
fruits.remove("apple")
removed_fruit = fruits.pop(1)
print(fruits)
print(removed_fruit)

['cherry', 'grape', 'peach']
kiwi


In [21]:
numbers = [1, 2, 3, 4, 5]
numbers[1:4] = [10, 20, 30]
print(numbers)

[1, 10, 20, 30, 5]


In [32]:
del fruits[1]
print(fruits)

['cherry', 'peach']


In [33]:
fruits.clear()
print(fruits)

[]


In [34]:
num_elements = len(numbers)
print(num_elements)

5


In [35]:
nested_list = [[1, 2, 3], ["a", "b", "c"]]
print(nested_list[0][1]) # najprej poveš katero množico gledaš, nato pa še kater element v tej množici

2


# TUPLES

Jih ne moremo manipulirati

In [4]:
fruits_tuple = ("apple", "banana", "orange")
numbers_tuple = 1, 2, 3
mixed_tuple = (1, "apple", 3.14, True)
empty_tuple = ()
single_element_tuple = ("apple",)
print(fruits_tuple)
print(numbers_tuple)
print(mixed_tuple)
print(empty_tuple)
print(single_element_tuple)

('apple', 'banana', 'orange')
(1, 2, 3)
(1, 'apple', 3.14, True)
()
('apple',)


In [6]:
first_fruit = fruits_tuple[0]
last_fruit = fruits_tuple[-1]
print(first_fruit)
print(last_fruit)

apple
orange


In [8]:
numbers_tuple = (1, 2, 3, 4, 5)
subset = numbers_tuple[1:4]
subset_start = numbers_tuple[:3] # Equivalent to numbers_tuple[0:3]
subset_end = numbers_tuple[2:]  # Equivalent to numbers_tuple[2:len(numbers_tuple)]
print(subset)
print(subset_start)
print(subset_end)

(2, 3, 4)
(1, 2, 3)
(3, 4, 5)


In [9]:
nested_tuple = ([1, 2, 3], "apple")
nested_tuple[0][1] = 10 # Valid, as the list inside the tuple is mutable
print(nested_tuple)

([1, 10, 3], 'apple')


### Basic tuple unpacking

In [11]:
# Creating a tuple
coordinates = (3, 7)

# Tuple unpacking
x, y = coordinates  # Variables x and y now hold the values 3 and 7, respectively

print(x)
print(y)

3
7


In [13]:
def get_coordinates():
    return 5, 10
# Calling the function and unpacking the result
x, y = get_coordinates()
# x is now 5, y is now 10
print(x)
print(y)

5
10


### Extended unpacking

In [17]:
# Creating a tuple
numbers = (1, 2, 3, 4, 5)
# Unpacking with extended unpacking
first, *rest, last = numbers
# first is 1, rest is [2, 3, 4], last is 5
print(first)
print(rest)
print(last)

1
[2, 3, 4]
5


In [18]:
# Creating a tuple
point = (8, 3, 5)
# Unpacking and ignoring the middle value
x, _, z = point
# x is 8, z is 5
print(x)
print(z)

8
5


# DICTIONARIES

In [29]:
# Creating a dictionary of student information
student = {
"name": "John Doe",
"age": 20,
"grade": "A",
"is_student": True,
"courses": ["Math", "Physics", "English"],
"grades": {"Math": "A", "Physics": "D", "English": "B"}
}
print(student)

{'name': 'John Doe', 'age': 20, 'grade': 'A', 'is_student': True, 'courses': ['Math', 'Physics', 'English'], 'grades': {'Math': 'A', 'Physics': 'D', 'English': 'B'}}


In [24]:
# Creating an empty dictionary
empty_dict = {}

In [1]:
fruit_dict = dict(apple=3, banana=5, orange=2)
print(fruit_dict)

{'apple': 3, 'banana': 5, 'orange': 2}


In [4]:
# Accessing elements using keys
student_name = student["name"]
student_age = student["age"]
print(student_name)
print(student_age)

John Doe
20


In [8]:
# Providing a default value with get()
instructor = student.get("instructor", "Not specified")
# If "instructor" key exists, instructor will contain its value; otherwise, it will be "Not specified"
print(instructor)


Not specified


In [18]:
physics_grade = student.get("grades", {}).get("Physics")
print(physics_grade)

D


In [21]:
# Using get() to handle key errors
color = student.get("favourite color")
# If "favourite color" key exists, grade will contain its value; otherwise, it will be None
print(color)

None


In [24]:
# Checking if a key exists
if "courses" in student:
    student_courses = student["courses"]
    print("if")
else:
    student_courses = []
    print("else")

if


In [33]:
# Accessing keys, values, and items
all_keys = student.keys()
all_values = student.values()
all_items = student.items()
print(all_keys)
print(all_values)
print(all_items)

dict_keys(['name', 'age', 'grade', 'is_student', 'courses', 'grades', 'gender', 'city'])
dict_values(['John Doe', 21, 'A', True, ['Math', 'Physics', 'English'], {'Math': 'A', 'Physics': 'D', 'English': 'B'}, 'Male', 'New York'])
dict_items([('name', 'John Doe'), ('age', 21), ('grade', 'A'), ('is_student', True), ('courses', ['Math', 'Physics', 'English']), ('grades', {'Math': 'A', 'Physics': 'D', 'English': 'B'}), ('gender', 'Male'), ('city', 'New York')])


In [27]:
# Modifying the value associated with the "age" key
student["age"] = 21
all_items = student.items()
print(all_items)

dict_items([('name', 'John Doe'), ('age', 21), ('grade', 'A'), ('is_student', True), ('courses', ['Math', 'Physics', 'English']), ('grades', {'Math': 'A', 'Physics': 'D', 'English': 'B'})])


In [28]:
# Adding a new key-value pair for the "gender" information
student["gender"] = "Male"
all_items = student.items()
print(all_items)

dict_items([('name', 'John Doe'), ('age', 21), ('grade', 'A'), ('is_student', True), ('courses', ['Math', 'Physics', 'English']), ('grades', {'Math': 'A', 'Physics': 'D', 'English': 'B'}), ('gender', 'Male')])


In [34]:
# Modifying and adding multiple elements
student.update({"age": 21, "gender": "Male", "city": "New York"})
all_keys = student.keys()
all_items = student.items()
print(all_items)
print(all_keys)

dict_items([('name', 'John Doe'), ('age', 21), ('grade', 'A'), ('is_student', True), ('courses', ['Math', 'Physics', 'English']), ('grades', {'Math': 'A', 'Physics': 'D', 'English': 'B'}), ('gender', 'Male'), ('city', 'New York')])
dict_keys(['name', 'age', 'grade', 'is_student', 'courses', 'grades', 'gender', 'city'])


In [35]:
# Removing the "grade" key and its value
del student["grade"]
all_items = student.items()
print(all_items)

dict_items([('name', 'John Doe'), ('age', 21), ('is_student', True), ('courses', ['Math', 'Physics', 'English']), ('grades', {'Math': 'A', 'Physics': 'D', 'English': 'B'}), ('gender', 'Male'), ('city', 'New York')])


In [36]:
# Removing and retrieving the value associated with the "courses" key
courses = student.pop("courses")
all_items = student.items()
print(all_items)

dict_items([('name', 'John Doe'), ('age', 21), ('is_student', True), ('grades', {'Math': 'A', 'Physics': 'D', 'English': 'B'}), ('gender', 'Male'), ('city', 'New York')])


In [37]:
# Removing and retrieving the last key-value pair
last_item = student.popitem()
print(last_item)

('city', 'New York')


In [38]:
# Clearing all elements from the dictionary
student.clear()
print(student)

{}


# SETS

In [39]:
# Creating a set with explicit elements
fruits_set = {"apple", "banana", "orange"}
# Creating an empty set
empty_set = set()
print(fruits_set)

{'banana', 'apple', 'orange'}


In [40]:
# Creating a set from a list
colors_list = ["red", "green", "blue", "red"]
colors_set = set(colors_list)
print(colors_set)

{'red', 'green', 'blue'}


In [41]:
# Adding a single element
fruits_set.add("kiwi")
print(fruits_set)

{'banana', 'kiwi', 'apple', 'orange'}


In [42]:
# Adding multiple elements
fruits_set.update(["grape", "pineapple"])
print(fruits_set)

{'grape', 'orange', 'banana', 'kiwi', 'pineapple', 'apple'}


In [43]:
# Removing a specific element
fruits_set.remove("banana")
print(fruits_set)

{'grape', 'orange', 'kiwi', 'pineapple', 'apple'}


In [44]:
# Discarding an element
fruits_set.discard("kiwi")
print(fruits_set)

{'grape', 'orange', 'pineapple', 'apple'}


In [45]:
# Pop an arbitrary element
popped_element = fruits_set.pop()
print(fruits_set)

{'orange', 'pineapple', 'apple'}
The history saving thread hit an unexpected error (OperationalError('database is locked')).History will not be written to the database.


In [46]:
# Clearing all elements from the set
fruits_set.clear()
print(fruits_set)

set()


### Set operations

In [47]:
set1 = {1,2,3}
set2 = {3,4,5}

In [48]:
union_set = set1 | set2  # # or using method: union_set = set1.union(set2)
print(union_set)

{1, 2, 3, 4, 5}


In [49]:
intersection_set = set1 & set2 # or using method: intersection_set = set1.intersection(set2)
print(intersection_set)

{3}


In [50]:
difference_set = set1 - set2 # or using method: difference_set = set1.difference(set2)
print(difference_set)

{1, 2}


In [52]:
symmetric_difference_set = set1 ^ set2 # or using method: symmetric_difference_set = set1.symmetric_difference (set2)
print(symmetric_difference_set)

{1, 2, 4, 5}


# CONTROL STRUCTURES

## IF STATEMENTS

In [53]:
x = 10
if x > 5:
    print("x is greater than 5")

x is greater than 5


In [54]:
x = 3
if x % 2 == 0:   # deliš x z 2 in čekiraš ali dobiš ostanek ali ne, če ni ostanka (je 0), je potem if statement true (x is even), drugače je pa false (x is odd)
    print("x is even")
else:
    print("x is odd")

x is odd


In [55]:
x = 0
if x > 0:
    print("x is positive")
elif x < 0:
    print("x is negative")
else:
    print("x is zero")

x is zero


### FOR LOOP

In [56]:
fruits = ["apple", "banana", "orange"]
for fruit in fruits:
    print(fruit)

apple
banana
orange


### WHILE LOOP

In [57]:
count = 0
while count < 5:
    print(count)
    count += 1

0
1
2
3
4


# FUNCTIONS

In [59]:
def add_numbers(a, b):
    sum_result = a + b
    return sum_result  # sends the result back to the place where the function was called
    
# Calling the function
result = add_numbers(5, 3)
print(result) 

8


In [60]:
def greet(name):
    greeting_message = f"Hello, {name}!"
    return greeting_message
    
# Calling the function
message = greet("Alice")
print(message)

Hello, Alice!


In [64]:
def square_number(number, power=2):
    result = number ** power
    return result
    
# Calling the function
square_result = square_number(4)
print(square_result)

16


In [65]:
# Calling the function with a different power
cube_result = square_number(4, 3)
print(cube_result) # Output: 64

64


In [66]:
add_numbers = lambda x, y: x + y
result = add_numbers(5,3)
print(result)

8


In [67]:
square = lambda x: x ** 2
result = square(4)
print(result)

16


In [68]:
is_even = lambda x: x % 2 == 0
result = is_even(7)
print(result) # Output: False

False


# MODULES

In [70]:
# my_module.py
def add(a, b):
    return a + b
def subtract(a, b):
    return a - b

In [71]:
# main_program.py
import my_module
result = my_module.add(5, 3)
print(result) # Output: 8

ModuleNotFoundError: No module named 'my_module'

# PACKAGES

In [73]:
#my_package/
#|-- __init__.py
#|-- module1.py
#|-- module2.py

In [72]:
# main_program.py
from my_package import module1
result = module1.square(4)
print(result) # Output: 16

ModuleNotFoundError: No module named 'my_package'

# WORKING WITH FILES

In [ ]:
file = open("filename.txt", "mode") # mode: r, w, a, rb, wb, rt, wt

In [ ]:
with open("example.txt", "r") as file:
    content = file.read()
    print(content)
    # perform operations with content
# file is automatically closed outside the "with" block

In [ ]:
with open("example.txt", "r") as file:
    line = file.readline()
        while line:
            print(line.strip()) # strip() removes newline characters
                line = file.readline()

In [ ]:
with open("example.txt", "r") as file:
    lines = file.readlines()
    for line in lines:
        print(line.strip())

In [75]:
with open("output.txt", "w") as file:
    file.write("This is a sample sentence.")

In [76]:
with open("output.txt", "a") as file:
    file.write("\nAppending new content.")

In [80]:
lines = ["\nLine 1\n", "Line 2\n", "Line 3\n"]
with open("output.txt", "a") as file:
    file.writelines(lines)

In [81]:
import math

result = math.sqrt(25)
print(result)

5.0


In [82]:
from math import sqrt  # eliminates the need to prefix the function with the library name when used

result = sqrt(25)
print(result)

5.0


In [ ]:
# Example: Using an alias for the pandas library, This is a common convention to simplify code and make it more readable
import pandas as pd
data = pd.read_csv("data.csv")
print(data.head())

In [85]:
#Example: Importing all modules from the datetime library
from datetime import *
current_date = date.today()
print(current_date) 

2025-10-09


# Object Oriented Programming in Python

In [6]:
class Car:
    def __init__(self, make, model, year):
        self.make = make
        self.model = model
        self.year = year
        
    def display_info(self):
        return f"{self.year} {self.make} {self.model}"

In [10]:
# Creating objects of the Car class
car1 = Car("Toyota", "Camry", 2022)
car2 = Car("Honda", "Civic", 2021)

# Accessing attributes and calling methods
print(car1.make)
print(car2.display_info())

Toyota
2021 Honda Civic


In [11]:
class Dog:
    def __init__(self, name, age):
        self.name = name
        self.age = age
        
    def bark(self):
        return "Woof!"
        
# Creating an object of the Dog class
my_dog = Dog("Buddy", 3)

# Accessing attributes and calling methods
print(my_dog.name) 
print(my_dog.bark())

Buddy
Woof!


### Example of Single Inheritance

In [15]:
# Base class
class Animal:
    def __init__(self, name):
        self.name = name
        
    def speak(self):
        return "Some generic sound"
        
# Derived class (inherits from Animal)
class Dog(Animal):
    def bark(self):
        return "Woof!"
        
# Creating objects
animal = Animal("Generic Animal")
dog = Dog("Buddy")

# Calling the speak method
print(animal.speak()) 
print(dog.speak())
print(dog.name)
print(dog.bark())

Some generic sound
Some generic sound
Buddy
Woof!


### Example of Multiple Inheritance

In [16]:
# Base classes
class Engine:
    def start(self):
        return "Engine started"

class Electric:
    def charge(self):
        return "Charging electric power"
        
# Derived class (inherits from both Engine and Electric)
class HybridCar(Engine, Electric):
    def drive(self):
        return "Driving in hybrid mode"
        
# Creating an object
hybrid_car = HybridCar()

# Accessing methods from the base classes
print(hybrid_car.start()) 
print(hybrid_car.charge()) 
print(hybrid_car.drive())       

Engine started
Charging electric power
Driving in hybrid mode


### Example of Multilevel Inheritance

In [17]:
# Base class
class Animal:
    def speak(self):
        return "Some generic sound"
        
# Intermediate class (inherits from Animal)
class Dog(Animal):
    def bark(self):
        return "Woof!"
        
# Derived class (inherits from Dog)
class Poodle(Dog):
    def dance(self):
        return "Poodle is dancing"
        
# Creating an object
poodle = Poodle()

# Accessing methods from all levels of inheritance
print(poodle.speak()) # Output: Some generic sound
print(poodle.bark()) # Output: Woof!
print(poodle.dance()) # Output: Poodle is dancing

Some generic sound
Woof!
Poodle is dancing


## Polymorphism in Python

In [18]:
class Shape:
    def area(self):
        return "Some generic area calculation"
        
class Square(Shape):
    def __init__(self, side):
        self.side = side
        
    def area(self):
        return self.side ** 2
        
class Circle(Shape):
    def __init__(self, radius):
        self.radius = radius
        
    def area(self):
        return 3.14 * self.radius ** 2
        
# Using polymorphism
shapes = [Square(5), Circle(3)]
for shape in shapes:
    print(f"Area: {shape.area()}")

Area: 25
Area: 28.26


# UPORABA KNJIŽNIC:

## NUMPY

In [1]:
import numpy as np
# Creating a 1D array from a Python list
arr1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr1d)

1D Array:
[1 2 3 4 5]


In [2]:
# Creating a 2D array from a nested Python list
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:")
print(arr2d)


2D Array:
[[1 2 3]
 [4 5 6]]


In [3]:
# Creating an array with mixed data types
mixed_array = np.array([1, 2.5, "hello"])
print("\nMixed Data Type Array:")
print(mixed_array)


Mixed Data Type Array:
['1' '2.5' 'hello']


In [4]:
# Specifying the data type of the array
arr_float = np.array([1, 2, 3], dtype=float)
print("\nArray with Specified Data Type (float):")
print(arr_float)


Array with Specified Data Type (float):
[1. 2. 3.]


In [5]:
import numpy as np
# Creating a 1D array filled with zeros
zeros_1d = np.zeros(5)
print("1D Array of Zeros:")
print(zeros_1d)

1D Array of Zeros:
[0. 0. 0. 0. 0.]


In [6]:
# Creating a 2D array filled with zeros
zeros_2d = np.zeros((3, 4)) # 3 rows, 4 columns
print("\n2D Array of Zeros:")
print(zeros_2d)


2D Array of Zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
# Creating a 1D array filled with ones
ones_1d = np.ones(6)
print("\n1D Array of Ones:")
print(ones_1d)


1D Array of Ones:
[1. 1. 1. 1. 1. 1.]


In [9]:
# Creating a 2D array filled with ones
ones_2d = np.ones((2, 3)) # 2 rows, 3 columns
print("\n2D Array of Ones:")
print(ones_2d)


2D Array of Ones:
[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
# Creating a 1D array filled with zeros with a specified data type
(float)
zeros_float = np.zeros(4, dtype=float)
print("\n1D Array of Zeros with Specified Data Type (float):")
print(zeros_float)


1D Array of Zeros with Specified Data Type (float):
[0. 0. 0. 0.]


In [13]:
# Creating a 2D array filled with ones with a specified data type (int)
ones_int = np.ones((3, 2), dtype=int)
print("\n2D Array of Ones with Specified Data Type (int):")
print(ones_int)


2D Array of Ones with Specified Data Type (int):
[[1 1]
 [1 1]
 [1 1]]


In [14]:
import numpy as np
# Creating a 1D array with values from 0 to 9
arr1d = np.arange(10)
print("1D Array:")
print(arr1d)

1D Array:
[0 1 2 3 4 5 6 7 8 9]


In [16]:
# Creating a 1D array with values from 2 to 10 (exclusive) with a step of 2
arr_custom = np.arange(2, 10, 2)
print("\nCustomized 1D Array:")
print(arr_custom)


Customized 1D Array:
[2 4 6 8]


In [19]:
# Creating a 1D array with floating-point values
arr_float = np.arange(0, 1, 0.1)
print("\n1D Array with Floating-Point Values:")
print(arr_float)


1D Array with Floating-Point Values:
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [22]:
# Creating a 1D array with specified data type (float)
arr_float_dtype = np.arange(5, dtype=float)
print("\n1D Array with Specified Data Type (float):")
print(arr_float_dtype)


1D Array with Specified Data Type (float):
[0. 1. 2. 3. 4.]


In [31]:
import numpy as np
# Creating a 1D array
arr1d = np.arange(12)
print("Original 1D Array:")
print(arr1d)
# Reshaping to a 2D array with 2 rows and 3 columns
arr2d = arr1d.reshape(2, 6)
print("\nReshaped 2D Array:")
print(arr2d)
# Reshaping to a 3D array with 2 planes, 2 rows, and 3 columns
arr3d = arr1d.reshape(2, 2, 3)
print("\nReshaped 3D Array:")
print(arr3d)

Original 1D Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped 2D Array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Reshaped 3D Array:
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [32]:
# Creating a 2D array
arr2d_original = np.array([[1, 2, 3], [4, 5, 6]])
print("\nOriginal 2D Array:")
print(arr2d_original)
# Reshaping to a flattened 1D array
arr_flattened = arr2d_original.reshape(-1)
print("\nFlattened 1D Array:")
print(arr_flattened)


Original 2D Array:
[[1 2 3]
 [4 5 6]]

Flattened 1D Array:
[1 2 3 4 5 6]


In [33]:
import numpy as np
# Creating a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original 2D Array:")
print(arr2d)
# Accessing elements using indexing
print("\nElement at row 1, column 2:", arr2d[1, 2])
# Slicing 1D array
print("Sliced row 2:", arr2d[1, :])
# Slicing 2D array
print("Sliced subarray:")
print(arr2d[:2, 1:])

Original 2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Element at row 1, column 2: 6
Sliced row 2: [4 5 6]
Sliced subarray:
[[2 3]
 [5 6]]


In [35]:
# Creating two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Concatenating 1D arrays
concatenated_arr = np.concatenate([arr1, arr2])
print("Concatenated 1D Array:")
print(concatenated_arr)

# Creating two 2D arrays
arr2d_1 = np.array([[1, 2], [3, 4]])
arr2d_2 = np.array([[5, 6]])

# Concatenating 2D arrays along rows (axis=0)
concatenated_2d_arr = np.concatenate([arr2d_1, arr2d_2], axis=0)
print("\nConcatenated 2D Array along Rows:")
print(concatenated_2d_arr)

Concatenated 1D Array:
[1 2 3 4 5 6]

Concatenated 2D Array along Rows:
[[1 2]
 [3 4]
 [5 6]]


In [36]:
# Creating a 2D array
arr2d_original = np.array([[1, 2, 3], [4, 5, 6]])
print("Original 2D Array:")
print(arr2d_original)

# Transposing the 2D array
arr2d_transposed = arr2d_original.T
print("\nTransposed 2D Array:")
print(arr2d_transposed)

Original 2D Array:
[[1 2 3]
 [4 5 6]]

Transposed 2D Array:
[[1 4]
 [2 5]
 [3 6]]


In [37]:
# Creating a 1D array
arr1d = np.arange(6)
print("Original 1D Array:")
print(arr1d)

# Reshaping to a 2D array with 2 rows and 3 columns
arr2d_reshaped = arr1d.reshape(2, 3)
print("\nReshaped 2D Array:")
print(arr2d_reshaped)

Original 1D Array:
[0 1 2 3 4 5]

Reshaped 2D Array:
[[0 1 2]
 [3 4 5]]


In [38]:
# Creating a 1D array
arr1d_to_split = np.array([1, 2, 3, 4, 5, 6])

# Splitting the 1D array into three parts
split_arr = np.split(arr1d_to_split, [2, 4])
print("Split Arrays:")
print(split_arr)

Split Arrays:
[array([1, 2]), array([3, 4]), array([5, 6])]


In [39]:
# Creating a 1D array
arr1d_original = np.array([1, 2, 3, 4, 5])

# Appending an element
arr1d_appended = np.append(arr1d_original, 6)
print("Appended 1D Array:")
print(arr1d_appended)

# Removing an element by index
arr1d_removed = np.delete(arr1d_original, 2)
print("\nArray after removing element at index 2:")
print(arr1d_removed)

Appended 1D Array:
[1 2 3 4 5 6]

Array after removing element at index 2:
[1 2 4 5]


In [42]:
import numpy as np
# Creating two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Addition
result_addition = arr1 + arr2
print("Addition:", result_addition)

# Subtraction
result_subtraction = arr1 - arr2
print("Subtraction:", result_subtraction)

# Multiplication
result_multiplication = arr1 * arr2
print("Multiplication:", result_multiplication)

# Division
result_division = arr1 / arr2
print("Division:", result_division)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [43]:
# Creating an array
arr = np.array([1, 2, 3, 4, 5])
# Square root
result_sqrt = np.sqrt(arr)
print("Square Root:", result_sqrt)
# Exponential
result_exp = np.exp(arr)
print("Exponential:", result_exp)
# Logarithm (natural logarithm)
result_log = np.log(arr)
print("Natural Logarithm:", result_log)
# Trigonometric functions
result_sin = np.sin(arr)
print("Sine:", result_sin)
result_cos = np.cos(arr)
print("Cosine:", result_cos)

Square Root: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Natural Logarithm: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Cosine: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [44]:
# Summation
sum_result = np.sum(arr)
print("Sum:", sum_result)

# Mean
mean_result = np.mean(arr)
print("Mean:", mean_result)

# Minimum and Maximum
min_value = np.min(arr)
max_value = np.max(arr)
print("Minimum:", min_value)
print("Maximum:", max_value)

Sum: 15
Mean: 3.0
Minimum: 1
Maximum: 5


In [1]:
import numpy as np
# Creating a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
# Broadcasting a scalar to the entire array
result_broadcasting = arr2d + 10
print("Broadcasting Result:")
print(result_broadcasting)

Broadcasting Result:
[[11 12 13]
 [14 15 16]]


In [3]:
# Using vectorized operations for element-wise square
arr = np.array([1, 2, 3, 4, 5])
result_squared = arr**2
print("Vectorized Square Operation:")
print(result_squared)

Vectorized Square Operation:
[ 1  4  9 16 25]


In [5]:
# Using a ufunc for element-wise square root
arr = np.array([1, 4, 9, 16, 25])
result_sqrt = np.sqrt(arr)
print("Element-wise Square Root using ufunc:")
print(result_sqrt)

Element-wise Square Root using ufunc:
[1. 2. 3. 4. 5.]


In [6]:
# Broadcasting a 1D array to a 2D array
arr1d = np.array([1, 2, 3])
arr2d = np.array([[10, 20, 30], [40, 50, 60]])
result_broadcasting_2d = arr1d + arr2d
print("Broadcasting 1D array to 2D array:")
print(result_broadcasting_2d)

Broadcasting 1D array to 2D array:
[[11 22 33]
 [41 52 63]]


## SciPy

In [8]:
import scipy
import numpy as np
# Check the version
print("SciPy Version:", scipy.__version__)
print("NumPy Version:", np.__version__)

SciPy Version: 1.16.0
NumPy Version: 2.0.2


In [9]:
import numpy as np
from scipy import linalg # Importing SciPy's linear algebra module
# Creating a 1D array
arr_1d = np.array([1, 2, 3])
# Creating a 2D matrix
matrix_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("1D Array:")
print(arr_1d)
print("\n2D Matrix:")
print(matrix_2d)

1D Array:
[1 2 3]

2D Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# Coefficient matrix
coeff_matrix = np.array([[2, 1], [3, -1]]) # 2x + y = 8 in 3x - y = 1
# Right-hand side
rhs_vector = np.array([8, 1])
# Solving the linear system
solution = linalg.solve(coeff_matrix, rhs_vector)
print("Solution to the Linear System:")
print(solution)

Solution to the Linear System:
[1.8 4.4]


In [11]:
# Matrix A
matrix_A = np.array([[4, -2], [1, 1]])
# Computing eigenvalues and eigenvectors
eigenvalues, eigenvectors = linalg.eig(matrix_A)
print("Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[3.+0.j 2.+0.j]

Eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [12]:
# Matrix B
matrix_B = np.array([[1, 2], [2, 3]])
# Computing Singular Value Decomposition
U, S, Vt = linalg.svd(matrix_B)
print("U matrix:")
print(U)
print("\nS matrix (singular values):")
print(S)
print("\nVt matrix (transpose of V):")
print(Vt)

U matrix:
[[-0.52573111 -0.85065081]
 [-0.85065081  0.52573111]]

S matrix (singular values):
[4.23606798 0.23606798]

Vt matrix (transpose of V):
[[-0.52573111 -0.85065081]
 [ 0.85065081 -0.52573111]]


In [15]:
# Consider integrating f(x) = x2 over the interval [0, 1]
from scipy import integrate
# Function to integrate
def func(x):
    return x**2
# Numerical integration
result, error = integrate.quad(func, 0, 1)
print("Result of Numerical Integration:")
print(result)

Result of Numerical Integration:
0.33333333333333337


In [19]:
import numpy as np

# Function to differentiate
def func_g(x):
    return np.exp(x)

# Numerical derivative using central finite difference
x = 2.0
dx = 1e-6
derivative_at_2 = (func_g(x + dx) - func_g(x - dx)) / (2 * dx)

print("Result of Numerical Differentiation at x=2:")
print(derivative_at_2)


Result of Numerical Differentiation at x=2:
7.3890560989831044


## Panda

In [8]:
import pandas as pd

# Creating a DataFrame from a dictionary
data = {'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'San Francisco', 'Los Angeles']}
df = pd.DataFrame(data)
print('DataFrame from a dictionary:')
print(df)

DataFrame from a dictionary:
      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles


In [4]:
# Creating a DataFrame from a list of lists
data_list = [['Alice', 25, 'New York'],
    ['Bob', 30, 'San Francisco'],
    ['Charlie', 35, 'Los Angeles']]
df_from_list = pd.DataFrame(data_list, columns=['Name', 'Age', 'City'])
print("DataFrame from List of Lists:")
print(df_from_list)

DataFrame from List of Lists:
      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles


In [6]:
import numpy as np
# Creating a DataFrame from a NumPy array
data_array = np.array([['Alice', 25, 'New York'],
    ['Bob', 30, 'San Francisco'],
    ['Charlie', 35, 'Los Angeles']])
df_from_array = pd.DataFrame(data_array, columns=['Name', 'Age','City'])
print("DataFrame from NumPy Array:")
print(df_from_array)

DataFrame from NumPy Array:
      Name Age           City
0    Alice  25       New York
1      Bob  30  San Francisco
2  Charlie  35    Los Angeles


In [9]:
# Creating a Series from a list
ages = pd.Series([25, 30, 35], name='Age')
print('Series from List:')
print(ages)

Series from List:
0    25
1    30
2    35
Name: Age, dtype: int64


In [10]:
import numpy as np
# Creating a Series from a NumPy array
ages_array = np.array([25, 30, 35])
ages_series_np = pd.Series(ages_array, name='Age')
print("Series from NumPy Array:")
print(ages_series_np)

Series from NumPy Array:
0    25
1    30
2    35
Name: Age, dtype: int64


### Handling Missing Data

In [11]:
import pandas as pd
import numpy as np
# Creating a DataFrame with missing values
data = {'Name': ['Alice', 'Bob', np.nan, 'Charlie'],
    'Age': [25, np.nan, 35, 40],
    'City': ['New York', 'San Francisco', 'Los Angeles', np.nan]}
df = pd.DataFrame(data)
# Identifying missing values using isnull() and sum()
missing_values_count = df.isnull().sum()
print("DataFrame with Missing Values:")
print(df)
print("\nMissing Values Count:")
print(missing_values_count)

DataFrame with Missing Values:
      Name   Age           City
0    Alice  25.0       New York
1      Bob   NaN  San Francisco
2      NaN  35.0    Los Angeles
3  Charlie  40.0            NaN

Missing Values Count:
Name    1
Age     1
City    1
dtype: int64


In [12]:
# Handling missing values using dropna()
df_cleaned_dropna = df.dropna()
# Handling missing values using fillna()
df_cleaned_fillna = df.fillna({'Name': 'Unknown', 'Age': 0, 'City':
'Unknown'})
print("\nDataFrame after Dropna:")
print(df_cleaned_dropna)
print("\nDataFrame after Fillna:")
print(df_cleaned_fillna)


DataFrame after Dropna:
    Name   Age      City
0  Alice  25.0  New York

DataFrame after Fillna:
      Name   Age           City
0    Alice  25.0       New York
1      Bob   0.0  San Francisco
2  Unknown  35.0    Los Angeles
3  Charlie  40.0        Unknown


### Dealing with Duplicates

In [13]:
import pandas as pd
# Creating a DataFrame with duplicate rows
data = {'Name': ['Alice', 'Bob', 'Alice', 'Charlie', 'Bob'],
    'Age': [25, 30, 25, 35, 30],
    'City': ['New York', 'San Francisco', 'New York', 'Los Angeles', 'San Francisco']}
df = pd.DataFrame(data)
# Identifying duplicates using duplicated()
duplicates = df[df.duplicated()]
print("DataFrame with Duplicates:")
print(df)
print("\nIdentified Duplicates:")
print(duplicates)

DataFrame with Duplicates:
      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2    Alice   25       New York
3  Charlie   35    Los Angeles
4      Bob   30  San Francisco

Identified Duplicates:
    Name  Age           City
2  Alice   25       New York
4    Bob   30  San Francisco


In [1]:
import pandas as pd
# Creating a DataFrame
data = {'Date': ['2022-01-01', '2022-01-01', '2022-01-02', '2022-01-02'],
    'Category': ['A', 'B', 'A', 'B'],
    'Value': [10, 20, 15, 25]}

df = pd.DataFrame(data)

# Reshaping with pivot
df_pivot = df.pivot(index='Date', columns='Category', values='Value')
print("Original DataFrame:")
print(df)
print("\nDataFrame after Pivot:")
print(df_pivot)

Original DataFrame:
         Date Category  Value
0  2022-01-01        A     10
1  2022-01-01        B     20
2  2022-01-02        A     15
3  2022-01-02        B     25

DataFrame after Pivot:
Category     A   B
Date              
2022-01-01  10  20
2022-01-02  15  25


In [2]:
# Creating a DataFrame
data = {'Date': ['2022-01-01', '2022-01-02'],
'Category_A': [10, 15],
'Category_B': [20, 25]}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)
# Melting data with the melt function
df_melted = pd.melt(df, id_vars=['Date'], var_name='Category',
value_name='Value')
print("\nDataFrame after Melting:")
print(df_melted)

Original DataFrame:
         Date  Category_A  Category_B
0  2022-01-01          10          20
1  2022-01-02          15          25

DataFrame after Melting:
         Date    Category  Value
0  2022-01-01  Category_A     10
1  2022-01-02  Category_A     15
2  2022-01-01  Category_B     20
3  2022-01-02  Category_B     25


In [3]:
import pandas as pd
from sklearn.impute import SimpleImputer
# Sample dataset with missing values
data = {'Age': [30, None, 50, 60],
'Income': [50000, 60000, None, 80000],
'Education_Level': [12, 16, 18, None]}
df = pd.DataFrame(data)
# Imputation using mean
imputer = SimpleImputer(strategy='mean')
df_imputed = pd.DataFrame(imputer.fit_transform(df), columns=df.columns)
print("Original DataFrame:")
print(df)
print("\nDataFrame after Imputation:")
print(df_imputed)

Original DataFrame:
    Age   Income  Education_Level
0  30.0  50000.0             12.0
1   NaN  60000.0             16.0
2  50.0      NaN             18.0
3  60.0  80000.0              NaN

DataFrame after Imputation:
         Age        Income  Education_Level
0  30.000000  50000.000000        12.000000
1  46.666667  60000.000000        16.000000
2  50.000000  63333.333333        18.000000
3  60.000000  80000.000000        15.333333


Debug sdf

In [4]:
from rdkit import Chem
from rdkit.Chem import AllChem, DataStructs, rdMolDescriptors

sdf_path = r"C:\Users\kuraltv\OneDriveUL\Documents\OUTPUT\InhA\AUTODOCK_results\Combined\Combined_Active_28.sdf"
suppl = Chem.SDMolSupplier(sdf_path)
for mol in suppl:
    if mol is None:
        continue
    print(mol.GetPropsAsDict().keys())
    break

dict_keys(['MODEL', 'REMARK', 'TORSDO', 'Affinity', 'RMSD_best', 'RMSD_input', 'INTER_INTRA', 'INTER', 'INTRA', 'UNBOUND', 'SMILES_IDX', 'Comment', 's_m_entry_id', 's_m_entry_name', 'Activity', 'Cluster number', 's_m_Source_Path', 's_m_Source_File', 'i_m_Source_File_Index', 's_m_source_file', 'i_m_source_file_index', 'i_lp_mmshare_version', 'i_f3d_flags', 's_epik_input', 's_epik_cmdline', 'r_epik_Ionization_Penalty', 'r_epik_Ionization_Penalty_Charging', 'r_epik_Ionization_Penalty_Neutral', 'r_epik_State_Penalty', 'r_epik_Charging_Adjusted_Penalty', 'i_epik_Tot_Q', 'i_epik_Tot_abs_Q', 's_lp_Force_Field', 'r_lp_Energy', 'b_lp_Chiralities_Consistent', 's_lp_Variant', 's_m_job_name', 's_m_subgroup_title', 's_m_subgroupid', 'b_m_subgroup_collapsed'])
